sudo: false
dist: xenial

language: node_js
node_js: 8.11

addons:
  chrome: stable

before_script:
  - npm install -g polymer-cli

script:
  - npm test

after_success:
  - npm install -g codecov
  - codecov
